import {
  Project,
  Task,
  Issue,
  Risk,
  Resource,
  Notification,
  Activity,
} from "@/types"

// ─── Projects ──────────────────────────────────────────────────

export const mockProjects: Project[] = [
  {
    id: "proj-001",
    name: "Campus Network Upgrade",
    description: "Complete network infrastructure overhaul for the main campus including fiber optic backbone installation and switch upgrades.",
    client: "Westfield University",
    projectManager: "Sarah Chen",
    projectType: "networking",
    status: "in-progress",
    health: "on-track",
    startDate: "2025-09-01",
    endDate: "2026-06-30",
    progress: 68,
    budget: 450000,
    spent: 285000,
    priority: "high",
    tags: ["fiber", "switches", "campus"],
    teamMembers: ["res-001", "res-003", "res-005"],
    createdAt: "2025-08-15",
    updatedAt: "2026-03-10",
  },
  {
    id: "proj-002",
    name: "City Center CCTV Installation",
    description: "Deploy 200+ CCTV cameras across the downtown district with centralized monitoring system.",
    client: "Metro City Council",
    projectManager: "James Rodriguez",
    projectType: "cctv",
    status: "in-progress",
    health: "at-risk",
    startDate: "2025-11-01",
    endDate: "2026-05-15",
    progress: 42,
    budget: 820000,
    spent: 510000,
    priority: "critical",
    tags: ["surveillance", "outdoor", "monitoring"],
    teamMembers: ["res-002", "res-004", "res-006"],
    createdAt: "2025-10-20",
    updatedAt: "2026-03-12",
  },
  {
    id: "proj-003",
    name: "Hotel WiFi Deployment",
    description: "Enterprise WiFi 6E deployment across 500-room luxury hotel with seamless roaming.",
    client: "Grand Horizon Hotels",
    projectManager: "Sarah Chen",
    projectType: "wifi",
    status: "completed",
    health: "completed",
    startDate: "2025-06-01",
    endDate: "2025-12-15",
    progress: 100,
    budget: 320000,
    spent: 298000,
    priority: "medium",
    tags: ["wifi6e", "hospitality", "roaming"],
    teamMembers: ["res-001", "res-005", "res-007"],
    createdAt: "2025-05-20",
    updatedAt: "2025-12-15",
  },
  {
    id: "proj-004",
    name: "Data Center Build - Phase 2",
    description: "Second phase of the enterprise data center build including server racks, cooling systems, and redundant power.",
    client: "TechCorp Industries",
    projectManager: "Michael Foster",
    projectType: "data-center",
    status: "in-progress",
    health: "critical",
    startDate: "2025-07-01",
    endDate: "2026-04-30",
    progress: 35,
    budget: 2400000,
    spent: 1680000,
    priority: "critical",
    tags: ["datacenter", "cooling", "power"],
    teamMembers: ["res-003", "res-004", "res-008"],
    createdAt: "2025-06-10",
    updatedAt: "2026-03-11",
  },
  {
    id: "proj-005",
    name: "Server Migration Project",
    description: "Migrate 50+ servers from legacy infrastructure to new hybrid cloud environment.",
    client: "FinanceFirst Bank",
    projectManager: "Emily Watson",
    projectType: "server",
    status: "planning",
    health: "on-track",
    startDate: "2026-04-01",
    endDate: "2026-09-30",
    progress: 8,
    budget: 680000,
    spent: 45000,
    priority: "high",
    tags: ["migration", "cloud", "hybrid"],
    teamMembers: ["res-003", "res-007"],
    createdAt: "2026-02-15",
    updatedAt: "2026-03-12",
  },
  {
    id: "proj-006",
    name: "Industrial IoT Network",
    description: "Deploy IoT sensor network across manufacturing floor with edge computing nodes.",
    client: "AutoMake Manufacturing",
    projectManager: "James Rodriguez",
    projectType: "infrastructure",
    status: "in-progress",
    health: "on-track",
    startDate: "2025-12-01",
    endDate: "2026-07-31",
    progress: 55,
    budget: 560000,
    spent: 290000,
    priority: "medium",
    tags: ["iot", "sensors", "edge"],
    teamMembers: ["res-001", "res-006", "res-008"],
    createdAt: "2025-11-15",
    updatedAt: "2026-03-10",
  },
  {
    id: "proj-007",
    name: "Warehouse CCTV Expansion",
    description: "Expand existing CCTV coverage to new warehouse wing with AI-powered analytics.",
    client: "LogiStore Inc",
    projectManager: "Emily Watson",
    projectType: "cctv",
    status: "in-progress",
    health: "on-track",
    startDate: "2026-01-15",
    endDate: "2026-04-30",
    progress: 72,
    budget: 180000,
    spent: 125000,
    priority: "medium",
    tags: ["warehouse", "ai-analytics", "expansion"],
    teamMembers: ["res-002", "res-004"],
    createdAt: "2026-01-05",
    updatedAt: "2026-03-12",
  },
  {
    id: "proj-008",
    name: "Stadium WiFi Infrastructure",
    description: "High-density WiFi deployment for 60,000-seat stadium with DAS integration.",
    client: "Metro Sports Authority",
    projectManager: "Michael Foster",
    projectType: "wifi",
    status: "planning",
    health: "on-track",
    startDate: "2026-05-01",
    endDate: "2026-11-30",
    progress: 5,
    budget: 1200000,
    spent: 25000,
    priority: "high",
    tags: ["stadium", "high-density", "DAS"],
    teamMembers: ["res-005", "res-007"],
    createdAt: "2026-03-01",
    updatedAt: "2026-03-12",
  },
  {
    id: "proj-009",
    name: "Office Network Refresh",
    description: "Replace aging network equipment across 5 office floors with SD-WAN enabled infrastructure.",
    client: "Meridian Consulting",
    projectManager: "Sarah Chen",
    projectType: "networking",
    status: "on-hold",
    health: "at-risk",
    startDate: "2025-10-01",
    endDate: "2026-03-31",
    progress: 45,
    budget: 210000,
    spent: 142000,
    priority: "low",
    tags: ["sd-wan", "office", "refresh"],
    teamMembers: ["res-001", "res-003"],
    createdAt: "2025-09-20",
    updatedAt: "2026-03-08",
  },
  {
    id: "proj-010",
    name: "New Factory IT Rollout",
    description: "Complete IT infrastructure deployment for new manufacturing facility including network, servers, and security systems.",
    client: "AutoMake Manufacturing",
    projectType: "infrastructure",
    projectManager: "James Rodriguez",
    status: "in-progress",
    health: "on-track",
    startDate: "2025-08-01",
    endDate: "2026-08-31",
    progress: 39,
    budget: 1850000,
    spent: 640000,
    priority: "high",
    tags: ["factory", "full-rollout", "greenfield"],
    teamMembers: ["res-002", "res-004", "res-006", "res-008"],
    createdAt: "2025-07-15",
    updatedAt: "2026-03-12",
  },
]

// ─── Tasks ──────────────────────────────────────────────────────

export const mockTasks: Task[] = [
  // Campus Network Upgrade tasks
  {
    id: "task-001",
    projectId: "proj-001",
    parentId: null,
    title: "Phase 1 - Core Network",
    description: "Deploy core network switches and fiber backbone",
    assignee: "Alex Kim",
    priority: "high",
    status: "completed",
    startDate: "2025-09-01",
    endDate: "2025-12-15",
    progress: 100,
    type: "milestone",
    dependencies: [],
    createdAt: "2025-08-15",
    updatedAt: "2025-12-15",
  },
  {
    id: "task-002",
    projectId: "proj-001",
    parentId: "task-001",
    title: "Install fiber optic backbone",
    description: "Run fiber across buildings A, B, and C",
    assignee: "Alex Kim",
    priority: "high",
    status: "completed",
    startDate: "2025-09-15",
    endDate: "2025-11-30",
    progress: 100,
    type: "task",
    dependencies: [],
    createdAt: "2025-08-15",
    updatedAt: "2025-11-30",
  },
  {
    id: "task-003",
    projectId: "proj-001",
    parentId: "task-001",
    title: "Configure core switches",
    description: "Setup and configure Cisco Catalyst 9500 switches",
    assignee: "Priya Sharma",
    priority: "high",
    status: "completed",
    startDate: "2025-10-01",
    endDate: "2025-12-15",
    progress: 100,
    type: "task",
    dependencies: ["task-002"],
    createdAt: "2025-08-15",
    updatedAt: "2025-12-15",
  },
  {
    id: "task-004",
    projectId: "proj-001",
    parentId: null,
    title: "Phase 2 - Access Layer",
    description: "Deploy access layer switches and wireless APs",
    assignee: "Sarah Chen",
    priority: "high",
    status: "in-progress",
    startDate: "2026-01-05",
    endDate: "2026-04-30",
    progress: 60,
    type: "milestone",
    dependencies: ["task-001"],
    createdAt: "2025-12-20",
    updatedAt: "2026-03-10",
  },
  {
    id: "task-005",
    projectId: "proj-001",
    parentId: "task-004",
    title: "Install access switches - Building A",
    description: "Deploy and configure 24 access switches",
    assignee: "Alex Kim",
    priority: "medium",
    status: "completed",
    startDate: "2026-01-05",
    endDate: "2026-02-15",
    progress: 100,
    type: "task",
    dependencies: [],
    createdAt: "2025-12-20",
    updatedAt: "2026-02-15",
  },
  {
    id: "task-006",
    projectId: "proj-001",
    parentId: "task-004",
    title: "Install access switches - Building B",
    description: "Deploy and configure 18 access switches",
    assignee: "Priya Sharma",
    priority: "medium",
    status: "in-progress",
    startDate: "2026-02-01",
    endDate: "2026-03-20",
    progress: 75,
    type: "task",
    dependencies: [],
    createdAt: "2025-12-20",
    updatedAt: "2026-03-10",
  },
  {
    id: "task-007",
    projectId: "proj-001",
    parentId: "task-004",
    title: "Deploy wireless APs",
    description: "Install and configure 120 wireless access points",
    assignee: "Li Wei",
    priority: "medium",
    status: "planned",
    startDate: "2026-03-01",
    endDate: "2026-04-30",
    progress: 10,
    type: "task",
    dependencies: ["task-005", "task-006"],
    createdAt: "2025-12-20",
    updatedAt: "2026-03-10",
  },
  {
    id: "task-008",
    projectId: "proj-001",
    parentId: null,
    title: "Phase 3 - Testing & Handover",
    description: "Full network testing, documentation, and client handover",
    assignee: "Sarah Chen",
    priority: "medium",
    status: "backlog",
    startDate: "2026-05-01",
    endDate: "2026-06-30",
    progress: 0,
    type: "milestone",
    dependencies: ["task-004"],
    createdAt: "2025-12-20",
    updatedAt: "2026-03-10",
  },
  // City Center CCTV tasks
  {
    id: "task-009",
    projectId: "proj-002",
    parentId: null,
    title: "Site Survey & Design",
    description: "Complete site surveys for all camera locations",
    assignee: "Marcus Johnson",
    priority: "high",
    status: "completed",
    startDate: "2025-11-01",
    endDate: "2025-12-15",
    progress: 100,
    type: "milestone",
    dependencies: [],
    createdAt: "2025-10-20",
    updatedAt: "2025-12-15",
  },
  {
    id: "task-010",
    projectId: "proj-002",
    parentId: null,
    title: "Camera Installation - Zone A",
    description: "Install 80 cameras in the downtown commercial area",
    assignee: "Marcus Johnson",
    priority: "critical",
    status: "in-progress",
    startDate: "2026-01-05",
    endDate: "2026-03-15",
    progress: 65,
    type: "milestone",
    dependencies: ["task-009"],
    createdAt: "2025-12-20",
    updatedAt: "2026-03-12",
  },
  {
    id: "task-011",
    projectId: "proj-002",
    parentId: null,
    title: "Camera Installation - Zone B",
    description: "Install 120 cameras in the residential areas",
    assignee: "Diana Torres",
    priority: "high",
    status: "planned",
    startDate: "2026-03-01",
    endDate: "2026-05-01",
    progress: 5,
    type: "milestone",
    dependencies: ["task-010"],
    createdAt: "2025-12-20",
    updatedAt: "2026-03-12",
  },
  {
    id: "task-012",
    projectId: "proj-002",
    parentId: null,
    title: "Monitoring Center Setup",
    description: "Build and configure central monitoring station",
    assignee: "James Rodriguez",
    priority: "high",
    status: "in-progress",
    startDate: "2026-02-01",
    endDate: "2026-04-30",
    progress: 30,
    type: "milestone",
    dependencies: [],
    createdAt: "2025-12-20",
    updatedAt: "2026-03-12",
  },
  // Data Center tasks
  {
    id: "task-013",
    projectId: "proj-004",
    parentId: null,
    title: "Server Rack Installation",
    description: "Install 40 server racks with cable management",
    assignee: "Raj Patel",
    priority: "critical",
    status: "in-progress",
    startDate: "2025-10-01",
    endDate: "2026-01-30",
    progress: 50,
    type: "milestone",
    dependencies: [],
    createdAt: "2025-06-10",
    updatedAt: "2026-03-11",
  },
  {
    id: "task-014",
    projectId: "proj-004",
    parentId: null,
    title: "Cooling System Deployment",
    description: "Install precision cooling units and hot/cold aisle containment",
    assignee: "Raj Patel",
    priority: "critical",
    status: "review",
    startDate: "2025-09-01",
    endDate: "2026-02-28",
    progress: 85,
    type: "milestone",
    dependencies: [],
    createdAt: "2025-06-10",
    updatedAt: "2026-03-11",
  },
  {
    id: "task-015",
    projectId: "proj-004",
    parentId: null,
    title: "Redundant Power Setup",
    description: "Deploy UPS systems and generator backup",
    assignee: "Michael Foster",
    priority: "critical",
    status: "planned",
    startDate: "2026-02-01",
    endDate: "2026-04-30",
    progress: 15,
    type: "milestone",
    dependencies: ["task-013"],
    createdAt: "2025-06-10",
    updatedAt: "2026-03-11",
  },
  // IoT Network tasks
  {
    id: "task-016",
    projectId: "proj-006",
    parentId: null,
    title: "Sensor Network Design",
    description: "Design IoT sensor placement and network topology",
    assignee: "Li Wei",
    priority: "high",
    status: "completed",
    startDate: "2025-12-01",
    endDate: "2026-01-15",
    progress: 100,
    type: "task",
    dependencies: [],
    createdAt: "2025-11-15",
    updatedAt: "2026-01-15",
  },
  {
    id: "task-017",
    projectId: "proj-006",
    parentId: null,
    title: "Edge Node Deployment",
    description: "Install edge computing nodes across factory floor",
    assignee: "Alex Kim",
    priority: "high",
    status: "in-progress",
    startDate: "2026-01-20",
    endDate: "2026-04-15",
    progress: 45,
    type: "milestone",
    dependencies: ["task-016"],
    createdAt: "2025-12-15",
    updatedAt: "2026-03-10",
  },
  {
    id: "task-018",
    projectId: "proj-006",
    parentId: null,
    title: "Sensor Installation",
    description: "Deploy 500+ IoT sensors with calibration",
    assignee: "Diana Torres",
    priority: "medium",
    status: "planned",
    startDate: "2026-03-15",
    endDate: "2026-06-30",
    progress: 0,
    type: "milestone",
    dependencies: ["task-017"],
    createdAt: "2025-12-15",
    updatedAt: "2026-03-10",
  },
]

// ─── Issues ─────────────────────────────────────────────────────

export const mockIssues: Issue[] = [
  {
    id: "issue-001",
    projectId: "proj-002",
    title: "Camera firmware incompatibility with NVR",
    description: "New batch of cameras has firmware v4.2 which is not compatible with current NVR system v3.8",
    severity: "critical",
    status: "in-progress",
    assignee: "Marcus Johnson",
    reportedBy: "Diana Torres",
    resolutionDate: null,
    createdAt: "2026-03-05",
    updatedAt: "2026-03-12",
  },
  {
    id: "issue-002",
    projectId: "proj-004",
    title: "Cooling unit noise exceeds specifications",
    description: "Precision cooling units in Row C generating 72dB noise, exceeding 65dB spec limit",
    severity: "high",
    status: "open",
    assignee: "Raj Patel",
    reportedBy: "Michael Foster",
    resolutionDate: null,
    createdAt: "2026-03-08",
    updatedAt: "2026-03-10",
  },
  {
    id: "issue-003",
    projectId: "proj-001",
    title: "Fiber splice loss above threshold",
    description: "Building B fiber runs showing 0.8dB splice loss, above 0.5dB threshold",
    severity: "medium",
    status: "resolved",
    assignee: "Alex Kim",
    reportedBy: "Priya Sharma",
    resolutionDate: "2026-03-09",
    createdAt: "2026-03-02",
    updatedAt: "2026-03-09",
  },
  {
    id: "issue-004",
    projectId: "proj-006",
    title: "Edge node overheating in section 4",
    description: "Temperature sensors report 82°C on edge node EN-04, above safe operating threshold of 75°C",
    severity: "high",
    status: "in-progress",
    assignee: "Li Wei",
    reportedBy: "Alex Kim",
    resolutionDate: null,
    createdAt: "2026-03-10",
    updatedAt: "2026-03-12",
  },
  {
    id: "issue-005",
    projectId: "proj-002",
    title: "Power supply shortage for Zone A cameras",
    description: "PoE budget exhausted on 3 switches in Zone A, need additional PoE injectors",
    severity: "high",
    status: "open",
    assignee: "James Rodriguez",
    reportedBy: "Marcus Johnson",
    resolutionDate: null,
    createdAt: "2026-03-11",
    updatedAt: "2026-03-12",
  },
  {
    id: "issue-006",
    projectId: "proj-001",
    title: "VLAN configuration mismatch",
    description: "Access switches in Building A configured with wrong VLAN assignment for guest network",
    severity: "low",
    status: "resolved",
    assignee: "Priya Sharma",
    reportedBy: "Sarah Chen",
    resolutionDate: "2026-02-28",
    createdAt: "2026-02-25",
    updatedAt: "2026-02-28",
  },
  {
    id: "issue-007",
    projectId: "proj-004",
    title: "Cable tray capacity exceeded in Row D",
    description: "Cable tray pathway in Row D at 110% capacity; need expansion or reroute",
    severity: "medium",
    status: "open",
    assignee: "Raj Patel",
    reportedBy: "Michael Foster",
    resolutionDate: null,
    createdAt: "2026-03-07",
    updatedAt: "2026-03-12",
  },
  {
    id: "issue-008",
    projectId: "proj-010",
    title: "Delayed equipment delivery",
    description: "Core switch shipment delayed by 3 weeks due to supply chain issues",
    severity: "critical",
    status: "open",
    assignee: "James Rodriguez",
    reportedBy: "Diana Torres",
    resolutionDate: null,
    createdAt: "2026-03-06",
    updatedAt: "2026-03-12",
  },
]

// ─── Risks ──────────────────────────────────────────────────────

export const mockRisks: Risk[] = [
  {
    id: "risk-001",
    projectId: "proj-004",
    title: "Budget overrun on cooling systems",
    description: "Custom cooling requirements may exceed Phase 2 budget allocation",
    impact: "critical",
    likelihood: "likely",
    mitigationPlan: "Negotiate volume pricing with alternative suppliers; prepare contingency budget approval",
    owner: "Michael Foster",
    status: "open",
    createdAt: "2025-08-01",
    updatedAt: "2026-03-10",
  },
  {
    id: "risk-002",
    projectId: "proj-002",
    title: "Permit delays for Zone B installation",
    description: "City permits for residential area camera installation may face community opposition",
    impact: "high",
    likelihood: "possible",
    mitigationPlan: "Begin community consultation process; prepare alternate mounting locations on public property",
    owner: "James Rodriguez",
    status: "open",
    createdAt: "2025-11-01",
    updatedAt: "2026-03-12",
  },
  {
    id: "risk-003",
    projectId: "proj-001",
    title: "Vendor certification delays",
    description: "Network engineering team needs updated Cisco certifications for new equipment",
    impact: "medium",
    likelihood: "unlikely",
    mitigationPlan: "Schedule certification exams in advance; identify backup certified engineers",
    owner: "Sarah Chen",
    status: "mitigated",
    createdAt: "2025-09-01",
    updatedAt: "2026-02-20",
  },
  {
    id: "risk-004",
    projectId: "proj-005",
    title: "Data loss during migration",
    description: "Risk of data corruption or loss during legacy server migration to cloud",
    impact: "critical",
    likelihood: "rare",
    mitigationPlan: "Multiple backup snapshots; staged migration with rollback capability; parallel running period",
    owner: "Emily Watson",
    status: "open",
    createdAt: "2026-02-15",
    updatedAt: "2026-03-12",
  },
  {
    id: "risk-005",
    projectId: "proj-006",
    title: "Sensor calibration drift",
    description: "IoT sensors may experience calibration drift in high-vibration factory environment",
    impact: "medium",
    likelihood: "possible",
    mitigationPlan: "Implement automated recalibration routines; install vibration dampers on sensitive sensors",
    owner: "James Rodriguez",
    status: "open",
    createdAt: "2026-01-10",
    updatedAt: "2026-03-10",
  },
  {
    id: "risk-006",
    projectId: "proj-010",
    title: "Supply chain disruption",
    description: "Key networking equipment supplier experiencing production delays",
    impact: "high",
    likelihood: "likely",
    mitigationPlan: "Identify secondary suppliers; pre-order critical components; maintain buffer inventory",
    owner: "James Rodriguez",
    status: "open",
    createdAt: "2026-02-01",
    updatedAt: "2026-03-12",
  },
]

// ─── Resources ──────────────────────────────────────────────────

export const mockResources: Resource[] = [
  {
    id: "res-001",
    name: "Alex Kim",
    email: "alex.kim@infrapro.com",
    role: "network-engineer",
    avatar: "",
    department: "Network Engineering",
    assignedTasks: 5,
    totalCapacity: 8,
    availability: 37,
    skills: ["Cisco", "Fiber Optics", "SD-WAN", "Routing"],
  },
  {
    id: "res-002",
    name: "Marcus Johnson",
    email: "marcus.j@infrapro.com",
    role: "cctv-technician",
    avatar: "",
    department: "Security Systems",
    assignedTasks: 4,
    totalCapacity: 8,
    availability: 50,
    skills: ["CCTV Installation", "NVR Configuration", "Video Analytics"],
  },
  {
    id: "res-003",
    name: "Priya Sharma",
    email: "priya.s@infrapro.com",
    role: "network-engineer",
    avatar: "",
    department: "Network Engineering",
    assignedTasks: 3,
    totalCapacity: 8,
    availability: 62,
    skills: ["Cisco", "Juniper", "Network Security", "VLANs"],
  },
  {
    id: "res-004",
    name: "Raj Patel",
    email: "raj.p@infrapro.com",
    role: "server-admin",
    avatar: "",
    department: "Data Center Operations",
    assignedTasks: 6,
    totalCapacity: 8,
    availability: 25,
    skills: ["Server Management", "Cooling Systems", "Power Distribution"],
  },
  {
    id: "res-005",
    name: "Li Wei",
    email: "li.wei@infrapro.com",
    role: "wifi-specialist",
    avatar: "",
    department: "Wireless Engineering",
    assignedTasks: 4,
    totalCapacity: 8,
    availability: 50,
    skills: ["WiFi 6E", "RF Design", "Site Survey", "Controllers"],
  },
  {
    id: "res-006",
    name: "Diana Torres",
    email: "diana.t@infrapro.com",
    role: "cctv-technician",
    avatar: "",
    department: "Security Systems",
    assignedTasks: 3,
    totalCapacity: 8,
    availability: 62,
    skills: ["CCTV Installation", "Cable Management", "IP Configuration"],
  },
  {
    id: "res-007",
    name: "Sarah Chen",
    email: "sarah.c@infrapro.com",
    role: "project-manager",
    avatar: "",
    department: "Project Management",
    assignedTasks: 3,
    totalCapacity: 6,
    availability: 50,
    skills: ["Project Management", "Stakeholder Management", "Agile"],
  },
  {
    id: "res-008",
    name: "Michael Foster",
    email: "michael.f@infrapro.com",
    role: "site-engineer",
    avatar: "",
    department: "Field Operations",
    assignedTasks: 4,
    totalCapacity: 8,
    availability: 50,
    skills: ["Site Management", "Power Systems", "Safety Compliance"],
  },
]

// ─── Notifications ──────────────────────────────────────────────

export const mockNotifications: Notification[] = [
  {
    id: "notif-001",
    title: "Critical Issue Raised",
    message: "Camera firmware incompatibility reported on City Center CCTV project",
    type: "error",
    read: false,
    createdAt: "2026-03-12T10:30:00",
    link: "/issues",
  },
  {
    id: "notif-002",
    title: "Project Milestone Completed",
    message: "Phase 1 - Core Network completed for Campus Network Upgrade",
    type: "success",
    read: false,
    createdAt: "2026-03-12T09:15:00",
    link: "/projects/proj-001",
  },
  {
    id: "notif-003",
    title: "Budget Warning",
    message: "Data Center Build - Phase 2 has exceeded 70% of budget",
    type: "warning",
    read: false,
    createdAt: "2026-03-11T16:45:00",
    link: "/projects/proj-004",
  },
  {
    id: "notif-004",
    title: "Task Assigned",
    message: "You have been assigned to 'Deploy wireless APs' on Campus Network Upgrade",
    type: "info",
    read: true,
    createdAt: "2026-03-11T14:20:00",
    link: "/projects/proj-001",
  },
  {
    id: "notif-005",
    title: "Equipment Delivery Delayed",
    message: "Core switch shipment for New Factory IT Rollout delayed by 3 weeks",
    type: "warning",
    read: true,
    createdAt: "2026-03-10T11:00:00",
    link: "/projects/proj-010",
  },
]

// ─── Activities ─────────────────────────────────────────────────

export const mockActivities: Activity[] = [
  {
    id: "act-001",
    projectId: "proj-001",
    user: "Alex Kim",
    action: "completed task",
    target: "Install access switches - Building A",
    timestamp: "2026-03-12T14:30:00",
  },
  {
    id: "act-002",
    projectId: "proj-002",
    user: "Marcus Johnson",
    action: "raised issue",
    target: "Camera firmware incompatibility with NVR",
    timestamp: "2026-03-12T10:30:00",
  },
  {
    id: "act-003",
    projectId: "proj-004",
    user: "Michael Foster",
    action: "updated risk",
    target: "Budget overrun on cooling systems",
    timestamp: "2026-03-11T16:45:00",
  },
  {
    id: "act-004",
    projectId: "proj-006",
    user: "Li Wei",
    action: "started task",
    target: "Edge Node Deployment",
    timestamp: "2026-03-11T09:00:00",
  },
  {
    id: "act-005",
    projectId: "proj-001",
    user: "Priya Sharma",
    action: "resolved issue",
    target: "Fiber splice loss above threshold",
    timestamp: "2026-03-09T15:20:00",
  },
  {
    id: "act-006",
    projectId: "proj-002",
    user: "James Rodriguez",
    action: "updated progress",
    target: "Camera Installation - Zone A (65%)",
    timestamp: "2026-03-09T11:45:00",
  },
  {
    id: "act-007",
    projectId: "proj-010",
    user: "Diana Torres",
    action: "reported issue",
    target: "Delayed equipment delivery",
    timestamp: "2026-03-08T10:15:00",
  },
  {
    id: "act-008",
    projectId: "proj-004",
    user: "Raj Patel",
    action: "submitted for review",
    target: "Cooling System Deployment",
    timestamp: "2026-03-07T17:30:00",
  },
]
